name: Node.js Package
on:
  push:
    branches:
      - master
 
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "2.0.0"
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: 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
